/// Digital input function numbers from Table 171 of the Open Protocol specification.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DigitalInputFunction {
  Off,
  ResetBatch,
  UnlockTool,
  ToolDisableNormallyOpen,
  ToolDisableNormallyClosed,
  ToolTighteningDisable,
  ToolLooseningDisable,
  RemoteStartPulse,
  RemoteStartContinuous,
  ToolStartLoosening,
  BatchIncrement,
  BypassParameterSet,
  AbortJob,
  JobOff,
  ParameterSetToggle,
  ResetRelays,
  ParameterSetSelectBit(u8),
  JobSelectBit(u8),
  BatchDecrement,
  JobRestart,
  EndOfCycle,
  ClickWrench(u8),
  IdCard,
  AutomaticMode,
  Reserved(u16),
  LineControlStart,
  LineControlAlert1,
  LineControlAlert2,
  AcknowledgeErrorMessage,
  FieldbusDigitalInput(u8),
  FlashToolGreenLight,
  ManualMode,
  ExternalMonitoredInput(u8),
  SelectNextParameterSet,
  SelectPreviousParameterSet,
  TimerEnableTool,
  MasterUnlockTool,
  ScanRequest,
  DisconnectTool,
  RequestScan,
  ResetNokCounter,
  BypassIdentifier,
  ResetLatestIdentifier,
  ResetAllIdentifiers,
  SetHomePosition,
  DigitalOutputMonitored(u8),
  DisableScanner,
  DisableFieldbusCarriedSignals,
  ToggleClockwiseCounterclockwise,
  ToggleClockwiseCounterclockwiseNextRun,
  SetCounterclockwise,
  OpenProtocolCommandsDisable,
  LogicDigitalInput(u8),
  ForcedCounterclockwiseOnce,
  ForcedCounterclockwiseToggle,
  ForcedClockwiseOnce,
  ForcedClockwiseToggle,
  ParameterSetSelectBit9,
  StoreCurrentTighteningProgram,
  ActiveXmlResultSend,
  ToolInWorkspace,
  ToolInProductSpace,
  FlashToolYellowLight,
  XmlEmergencyMode,
  MfuTest,
  ToolInParkPosition,
  EnableOperation,
  StopTightening,
  StartLooseningPulse,
  FreeToUse(u16),
  PulsorToolEnable,
  PerformAirHoseTest,
  LastDigitalInput,
  PulsorReserved(u16),
  ToolBlueLightIoControlled,
  ToolBlueLight,
  ToolGreenLightIoControlled,
  ToolGreenLight,
  ToolRedLightIoControlled,
  ToolRedLight,
  ToolYellowLightIoControlled,
  ToolYellowLight,
  ToolWhiteLightIoControlled,
  ToolWhiteLight,
}

impl DigitalInputFunction {
  pub fn value(self) -> u16 {
    match self {
      Self::Off => 0,
      Self::ResetBatch => 1,
      Self::UnlockTool => 2,
      Self::ToolDisableNormallyOpen => 3,
      Self::ToolDisableNormallyClosed => 4,
      Self::ToolTighteningDisable => 5,
      Self::ToolLooseningDisable => 6,
      Self::RemoteStartPulse => 7,
      Self::RemoteStartContinuous => 8,
      Self::ToolStartLoosening => 9,
      Self::BatchIncrement => 10,
      Self::BypassParameterSet => 11,
      Self::AbortJob => 12,
      Self::JobOff => 13,
      Self::ParameterSetToggle => 14,
      Self::ResetRelays => 15,
      Self::ParameterSetSelectBit(bit) => 16 + bit as u16,
      Self::JobSelectBit(bit) => 20 + bit as u16,
      Self::BatchDecrement => 53,
      Self::JobRestart => 54,
      Self::EndOfCycle => 55,
      Self::ClickWrench(tool) => 62 + tool as u16,
      Self::IdCard => 66,
      Self::AutomaticMode => 67,
      Self::Reserved(value) | Self::PulsorReserved(value) | Self::FreeToUse(value) => value,
      Self::LineControlStart => 28,
      Self::LineControlAlert1 => 29,
      Self::LineControlAlert2 => 30,
      Self::AcknowledgeErrorMessage => 31,
      Self::FieldbusDigitalInput(input) => 32 + input as u16,
      Self::FlashToolGreenLight => 36,
      Self::ManualMode => 43,
      Self::ExternalMonitoredInput(input) => 68 + input as u16,
      Self::SelectNextParameterSet => 76,
      Self::SelectPreviousParameterSet => 77,
      Self::TimerEnableTool => 79,
      Self::MasterUnlockTool => 80,
      Self::ScanRequest => 81,
      Self::DisconnectTool => 82,
      Self::RequestScan => 85,
      Self::ResetNokCounter => 86,
      Self::BypassIdentifier => 87,
      Self::ResetLatestIdentifier => 88,
      Self::ResetAllIdentifiers => 89,
      Self::SetHomePosition => 90,
      Self::DigitalOutputMonitored(input) => 91 + input as u16,
      Self::DisableScanner => 95,
      Self::DisableFieldbusCarriedSignals => 96,
      Self::ToggleClockwiseCounterclockwise => 97,
      Self::ToggleClockwiseCounterclockwiseNextRun => 98,
      Self::SetCounterclockwise => 99,
      Self::OpenProtocolCommandsDisable => 104,
      Self::LogicDigitalInput(input) => 105 + input as u16,
      Self::ForcedCounterclockwiseOnce => 120,
      Self::ForcedCounterclockwiseToggle => 121,
      Self::ForcedClockwiseOnce => 122,
      Self::ForcedClockwiseToggle => 123,
      Self::ParameterSetSelectBit9 => 129,
      Self::StoreCurrentTighteningProgram => 130,
      Self::ActiveXmlResultSend => 131,
      Self::ToolInWorkspace => 132,
      Self::ToolInProductSpace => 133,
      Self::FlashToolYellowLight => 134,
      Self::XmlEmergencyMode => 135,
      Self::MfuTest => 136,
      Self::ToolInParkPosition => 137,
      Self::EnableOperation => 138,
      Self::StopTightening => 139,
      Self::StartLooseningPulse => 140,
      Self::PulsorToolEnable => 150,
      Self::PerformAirHoseTest => 151,
      Self::LastDigitalInput => 152,
      Self::ToolBlueLightIoControlled => 201,
      Self::ToolBlueLight => 202,
      Self::ToolGreenLightIoControlled => 203,
      Self::ToolGreenLight => 204,
      Self::ToolRedLightIoControlled => 205,
      Self::ToolRedLight => 206,
      Self::ToolYellowLightIoControlled => 207,
      Self::ToolYellowLight => 208,
      Self::ToolWhiteLightIoControlled => 209,
      Self::ToolWhiteLight => 210,
    }
  }
}

impl TryFrom<u16> for DigitalInputFunction {
  type Error = String;

  fn try_from(value: u16) -> Result<Self, Self::Error> {
    let function = match value {
      0 => Self::Off,
      1 => Self::ResetBatch,
      2 => Self::UnlockTool,
      3 => Self::ToolDisableNormallyOpen,
      4 => Self::ToolDisableNormallyClosed,
      5 => Self::ToolTighteningDisable,
      6 => Self::ToolLooseningDisable,
      7 => Self::RemoteStartPulse,
      8 => Self::RemoteStartContinuous,
      9 => Self::ToolStartLoosening,
      10 => Self::BatchIncrement,
      11 => Self::BypassParameterSet,
      12 => Self::AbortJob,
      13 => Self::JobOff,
      14 => Self::ParameterSetToggle,
      15 => Self::ResetRelays,
      16..=19 => Self::ParameterSetSelectBit((value - 16) as u8),
      20..=23 => Self::JobSelectBit((value - 20) as u8),
      24..=27 | 37..=42 | 44 | 56..=61 | 78 | 83..=84 | 100..=103 | 115..=119 | 124..=128 => {
        Self::Reserved(value)
      }
      141..=149 => Self::FreeToUse(value),
      28 => Self::LineControlStart,
      29 => Self::LineControlAlert1,
      30 => Self::LineControlAlert2,
      31 => Self::AcknowledgeErrorMessage,
      32..=35 => Self::FieldbusDigitalInput((value - 32) as u8),
      36 => Self::FlashToolGreenLight,
      43 => Self::ManualMode,
      45..=48 => Self::ParameterSetSelectBit((value - 40) as u8),
      49..=52 => Self::JobSelectBit((value - 45) as u8),
      53 => Self::BatchDecrement,
      54 => Self::JobRestart,
      55 => Self::EndOfCycle,
      62..=65 => Self::ClickWrench((value - 62) as u8),
      66 => Self::IdCard,
      67 => Self::AutomaticMode,
      68..=75 => Self::ExternalMonitoredInput((value - 68) as u8),
      76 => Self::SelectNextParameterSet,
      77 => Self::SelectPreviousParameterSet,
      79 => Self::TimerEnableTool,
      80 => Self::MasterUnlockTool,
      81 => Self::ScanRequest,
      82 => Self::DisconnectTool,
      85 => Self::RequestScan,
      86 => Self::ResetNokCounter,
      87 => Self::BypassIdentifier,
      88 => Self::ResetLatestIdentifier,
      89 => Self::ResetAllIdentifiers,
      90 => Self::SetHomePosition,
      91..=94 => Self::DigitalOutputMonitored((value - 91) as u8),
      95 => Self::DisableScanner,
      96 => Self::DisableFieldbusCarriedSignals,
      97 => Self::ToggleClockwiseCounterclockwise,
      98 => Self::ToggleClockwiseCounterclockwiseNextRun,
      99 => Self::SetCounterclockwise,
      104 => Self::OpenProtocolCommandsDisable,
      105..=114 => Self::LogicDigitalInput((value - 105) as u8),
      120 => Self::ForcedCounterclockwiseOnce,
      121 => Self::ForcedCounterclockwiseToggle,
      122 => Self::ForcedClockwiseOnce,
      123 => Self::ForcedClockwiseToggle,
      129 => Self::ParameterSetSelectBit9,
      130 => Self::StoreCurrentTighteningProgram,
      131 => Self::ActiveXmlResultSend,
      132 => Self::ToolInWorkspace,
      133 => Self::ToolInProductSpace,
      134 => Self::FlashToolYellowLight,
      135 => Self::XmlEmergencyMode,
      136 => Self::MfuTest,
      137 => Self::ToolInParkPosition,
      138 => Self::EnableOperation,
      139 => Self::StopTightening,
      140 => Self::StartLooseningPulse,
      150 => Self::PulsorToolEnable,
      151 => Self::PerformAirHoseTest,
      152 => Self::LastDigitalInput,
      153..=200 => Self::PulsorReserved(value),
      201 => Self::ToolBlueLightIoControlled,
      202 => Self::ToolBlueLight,
      203 => Self::ToolGreenLightIoControlled,
      204 => Self::ToolGreenLight,
      205 => Self::ToolRedLightIoControlled,
      206 => Self::ToolRedLight,
      207 => Self::ToolYellowLightIoControlled,
      208 => Self::ToolYellowLight,
      209 => Self::ToolWhiteLightIoControlled,
      210 => Self::ToolWhiteLight,
      211..=299 | 300..=349 => Self::Reserved(value),
      _ => return Err(format!("Unsupported digital input function {}", value)),
    };
    Ok(function)
  }
}
